"""followers

Revision ID: 181087f58b59
Revises: e0764766e0fd
Create Date: 2019-12-13 16:20:25.933298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181087f58b59'
down_revision = 'e0764766e0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
